spring.datasource.afagoal:
  type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://47.98.36.205:3306/afagoal_apps?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
  username: afagoal_apps
  password: afagoal123.
  initialSize: 1
  minIdle: 3
  maxActive: 20
  maxIdleTime: 1800
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3600000
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 'x'
  testWhileIdle: true
  #testOnBorrow: false
  #testOnReturn: false
  #poolPreparedStatements: true
  #maxPoolPreparedStatementPerConnectionSize: 20
  #filters: stat,wall,slf4j
  #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #useGlobalDataSourceStat: true


afagoal.session.enable: true

server:
  port: 9090
